import { APP_STRIPE_KEY, BACKEND_API, GOOGLE_ANALYTICS, SUPABASE_ANON, SUPABASE_URL } from '@env';

const envConfig = {
    STRIPE_KEY: APP_STRIPE_KEY,
    SUPABASE_URL: SUPABASE_URL,
    SUPABASE_ANON: SUPABASE_ANON,
    GOOGLE_ANALYTICS: GOOGLE_ANALYTICS,
    BACKEND_API: BACKEND_API,
};

export default envConfig;
